# Generated by Django 5.2.6 on 2025-10-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facultad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
