# Generated by Django 5.2.6 on 2025-09-08 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultad', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('interno', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facultad.carrera')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voluntarios', to='personas.persona')),
            ],
        ),
    ]
