# Generated by Django 5.2.6 on 2025-10-28 18:15
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=150)),
                ('entidad_encargada', models.CharField(max_length=150)),
                # Use a static upload_to path to avoid importing from models at migration import time
                ('firma', models.FileField(blank=True, null=True, upload_to='certificado/autoridades/firmas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EncabezadoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('imagen_1', models.FileField(blank=True, null=True, upload_to='certificado/encabezados/imagen_1')),
                ('imagen_2', models.FileField(blank=True, null=True, upload_to='certificado/encabezados/imagen_2')),
                ('imagen_3', models.FileField(blank=True, null=True, upload_to='certificado/encabezados/imagen_3')),
                ('imagen_4', models.FileField(blank=True, null=True, upload_to='certificado/encabezados/imagen_4')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Encabezado de certificado',
                'verbose_name_plural': 'Encabezados de certificados',
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='certificado/%Y/%m/%d')),
                ('asistencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencia', to='asistencia.asistencia')),
                ('autoridades', models.ManyToManyField(related_name='certificados', to='certificado.autoridad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
