# Generated by Django 5.2.6 on 2025-09-15 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        ('voluntariado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voluntariado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voluntariado.voluntariado')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='persona.voluntario')),
            ],
        ),
    ]
