# Generated by Django 5.2.6 on 2025-09-16 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        ('voluntariado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('horas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('voluntariado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voluntariado.voluntariado')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='persona.voluntario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
