# Generated by Django 5.2.7 on 2025-10-28 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='autoridades',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='asistencia',
        ),
        migrations.DeleteModel(
            name='EncabezadoCertificado',
        ),
        migrations.DeleteModel(
            name='Autoridad',
        ),
        migrations.DeleteModel(
            name='Certificado',
        ),
    ]
