# Generated by Django 5.2.6 on 2025-10-01 17:52

import apps.certificado.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
        ('certificado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=150)),
                ('entidad_encargada', models.CharField(max_length=150)),
                ('firma', models.FileField(blank=True, null=True, upload_to=apps.certificado.models.authority_signature_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='horas',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='voluntariado',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='voluntario',
        ),
        migrations.AddField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='certificado/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='asistencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencia', to='asistencia.asistencia'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='autoridades',
            field=models.ManyToManyField(related_name='certificados', to='certificado.autoridad'),
        ),
    ]
