# Generated by Django 5.2.6 on 2025-09-08 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificado', '0002_initial'),
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='voluntario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='voluntarios.voluntario'),
        ),
    ]
