# Generated by Django 5.2.6 on 2025-10-23 01:26

import apps.certificado.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0002_autoridad_remove_certificado_fecha_emision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncabezadoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('imagen_1', models.FileField(blank=True, null=True, upload_to=apps.certificado.models.EncabezadoCertificado.encabezado_imagen_1_path)),
                ('imagen_2', models.FileField(blank=True, null=True, upload_to=apps.certificado.models.EncabezadoCertificado.encabezado_imagen_2_path)),
                ('imagen_3', models.FileField(blank=True, null=True, upload_to=apps.certificado.models.EncabezadoCertificado.encabezado_imagen_3_path)),
                ('imagen_4', models.FileField(blank=True, null=True, upload_to=apps.certificado.models.EncabezadoCertificado.encabezado_imagen_4_path)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Encabezado de certificado',
                'verbose_name_plural': 'Encabezados de certificados',
            },
        ),
    ]
