# Generated by Django 5.2.6 on 2025-10-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='registrada_at',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='registrada_por',
        ),
    ]
