# Generated by Django 5.2.7 on 2025-10-28 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        ('voluntariado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='inscripcion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='voluntariado.inscripcionturno'),
        ),
    ]
