# Generated by Django 5.2.6 on 2025-10-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='organizaciones/banners/'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizaciones/logos/'),
        ),
    ]
