# Generated by Django 5.2.6 on 2025-10-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_organizacion_banner_organizacion_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
