# Generated by Django 5.2.6 on 2025-10-01 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_alter_organizacion_contacto_persona'),
        ('ubicacion', '0001_initial'),
        ('voluntariado', '0003_descripcionvoluntariado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacion',
            options={'ordering': ('nombre',)},
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='contacto_persona',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='direccion',
        ),
        migrations.AddField(
            model_name='organizacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='voluntariado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voluntariado.voluntariado'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='organizacion',
            index=models.Index(fields=['nombre'], name='organizacio_nombre_c063a0_idx'),
        ),
    ]
