# Generated by Django 5.2.6 on 2025-10-10 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0003_alter_organizacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacion',
            name='voluntariado',
        ),
    ]
