# Generated by Django 5.2.6 on 2025-10-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0004_remove_organizacion_voluntariado'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
