# Generated by Django 5.2.6 on 2025-10-11 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('page_title', models.CharField(default='Sistema de Voluntariado', help_text='Título que aparece en la pestaña del navegador', max_length=100, verbose_name='Título de la página')),
                ('site_name', models.CharField(default='Voluntariado UNCuyo', help_text='Nombre principal del sitio web', max_length=100, verbose_name='Nombre del sitio')),
                ('hero_image', models.FileField(blank=True, help_text='Archivo de imagen de fondo o principal de la landing page', null=True, upload_to='landing/hero/', verbose_name='Imagen principal')),
                ('contact_email', models.EmailField(blank=True, help_text='Dirección de email principal para contacto', max_length=254, null=True, verbose_name='Email de contacto')),
                ('phone_number', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato válido (ej: +541234567890)', regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de teléfono')),
                ('instagram_handle', models.CharField(blank=True, help_text='Nombre de usuario de Instagram (sin @)', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='El handle de Instagram solo puede contener letras, números, puntos y guiones bajos', regex='^[a-zA-Z0-9_.]+$')], verbose_name='Instagram')),
                ('footer_text', models.TextField(blank=True, default='© 2025 Universidad Nacional de Cuyo. Todos los derechos reservados.', help_text='Texto que aparece en el pie de página', null=True, verbose_name='Texto del footer')),
                ('welcome_message', models.TextField(blank=True, default='Bienvenido al Sistema de Voluntariado', help_text='Mensaje principal de bienvenida en la landing page', null=True, verbose_name='Mensaje de bienvenida')),
                ('description', models.TextField(blank=True, help_text='Descripción breve del sitio para SEO y presentación', null=True, verbose_name='Descripción del sitio')),
            ],
            options={
                'verbose_name': 'Configuración de Landing',
                'verbose_name_plural': 'Configuración de Landing',
                'db_table': 'core_landing_config',
            },
        ),
    ]
