# Generated by Django 5.2.6 on 2025-10-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfig',
            name='how_it_works_steps',
            field=models.JSONField(blank=True, default=list, help_text='Array de objetos JSON [{title, description}]', verbose_name="Pasos 'Cómo Funciona'"),
        ),
        migrations.AddField(
            model_name='landingconfig',
            name='info_items',
            field=models.JSONField(blank=True, default=list, help_text='Array de objetos JSON [{icon, title, description}]', verbose_name="Items de Info ('Qué es')"),
        ),
        migrations.AddField(
            model_name='landingconfig',
            name='team_members',
            field=models.JSONField(blank=True, default=list, help_text='Array de objetos JSON [{name, role, imageUrl}] - imageUrl es opcional.', verbose_name='Miembros del Equipo'),
        ),
        migrations.AddField(
            model_name='landingconfig',
            name='testimonials',
            field=models.JSONField(blank=True, default=list, help_text='Array de objetos JSON [{name, role, text, imageUrl}] - imageUrl es opcional.', verbose_name='Testimonios'),
        ),
    ]
