# Generated by Django 5.2.6 on 2025-10-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_landingconfig_how_it_works_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfig',
            name='milestones',
            field=models.JSONField(blank=True, default=list, help_text='Array de objetos JSON [{year, title, description}] usado en About', verbose_name='Hitos / Línea de Tiempo'),
        ),
        migrations.AddField(
            model_name='landingconfig',
            name='mission',
            field=models.TextField(blank=True, help_text='Texto de la misión que aparece en la sección About', null=True, verbose_name='Misión'),
        ),
        migrations.AddField(
            model_name='landingconfig',
            name='offers_organizations',
            field=models.JSONField(blank=True, default=list, help_text='Array de strings con las ofertas dirigidas a organizaciones', verbose_name='Ofertas para Organizaciones'),
        ),
        migrations.AddField(
            model_name='landingconfig',
            name='offers_students',
            field=models.JSONField(blank=True, default=list, help_text='Array de strings con las ofertas dirigidas a estudiantes', verbose_name='Ofertas para Estudiantes'),
        ),
        migrations.AddField(
            model_name='landingconfig',
            name='stats',
            field=models.JSONField(blank=True, default=list, help_text='Array de objetos JSON [{number, label}] usado en About', verbose_name='Estadísticas'),
        ),
        migrations.AddField(
            model_name='landingconfig',
            name='values',
            field=models.JSONField(blank=True, default=list, help_text='Array de objetos JSON [{icon, title, description}] usado en About', verbose_name='Valores (cards)'),
        ),
        migrations.AddField(
            model_name='landingconfig',
            name='vision',
            field=models.TextField(blank=True, help_text='Texto de la visión que aparece en la sección About', null=True, verbose_name='Visión'),
        ),
    ]
