# Generated by Django 5.2.6 on 2025-10-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_landingconfig_base_hours'),
        ('core', '0003_landingconfig_milestones_landingconfig_mission_and_more'),
    ]

    operations = [
    ]
