# Generated by Django 5.2.6 on 2025-10-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_base_metrics_fields'),
        ('core', '0004_merge_20251028_0952'),
    ]

    operations = [
    ]
