# Generated by Django 5.2.6 on 2025-09-08 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultad', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('voluntariados', '0001_initial'),
        ('voluntarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionturno',
            name='voluntario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='voluntarios.voluntario'),
        ),
        migrations.AddField(
            model_name='inscripcionturno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='voluntariados.turno'),
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facultad.facultad'),
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voluntariados', to='organizacion.organizacion'),
        ),
        migrations.AddField(
            model_name='turno',
            name='voluntariado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='voluntariados.voluntariado'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionturno',
            unique_together={('turno', 'voluntario')},
        ),
    ]
