# Generated by Django 5.2.6 on 2025-10-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='codigo',
        ),
    ]
