# Generated by Django 5.2.7 on 2025-10-28 16:50

import apps.dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=apps.dashboard.models.generate_api_key, editable=False, max_length=64, unique=True, verbose_name='Clave de API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
            ],
            options={
                'verbose_name': 'Clave de API',
                'verbose_name_plural': 'Claves de API',
                'ordering': ['-created_at'],
            },
        ),
    ]
