# Generated by Django 5.2.6 on 2025-09-16 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultad', '__first__'),
        ('organizacion', '__first__'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Activo'), ('CLOSED', 'Cerrado')], default='DRAFT', max_length=10)),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facultad.facultad')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voluntariados', to='organizacion.organizacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cupo', models.PositiveIntegerField(default=1)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('voluntariado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='voluntariado.voluntariado')),
            ],
            options={
                'ordering': ('-fecha', 'hora_inicio'),
            },
        ),
        migrations.CreateModel(
            name='InscripcionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INS', 'Inscripto'), ('CAN', 'Cancelado'), ('ASI', 'Asistió')], default='INS', max_length=4)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='persona.voluntario')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='voluntariado.turno')),
            ],
            options={
                'unique_together': {('turno', 'voluntario')},
            },
        ),
    ]
