# Generated by Django 5.2.7 on 2025-10-28 16:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        ('persona', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionVoluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos')),
                ('portada', models.FileField(blank=True, null=True, upload_to='logos')),
                ('resumen', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cupo', models.PositiveIntegerField(default=1)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('-fecha', 'hora_inicio'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalDescripcionVoluntariado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('logo', models.TextField(blank=True, max_length=100, null=True)),
                ('portada', models.TextField(blank=True, max_length=100, null=True)),
                ('resumen', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical descripcion voluntariado',
                'verbose_name_plural': 'historical descripcion voluntariados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVoluntariado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=250)),
                ('requiere_convocatoria', models.BooleanField(default=True, verbose_name='Requiere convocatoria previa para inscribirse')),
                ('fecha_inicio_convocatoria', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de convocatoria')),
                ('fecha_fin_convocatoria', models.DateField(blank=True, null=True, verbose_name='Fecha de fin de convocatoria')),
                ('fecha_inicio_cursado', models.DateField(blank=True, verbose_name='Fecha de inicio de cursado')),
                ('fecha_fin_cursado', models.DateField(blank=True, verbose_name='Fecha de fin de cursado')),
                ('latitud', models.FloatField(blank=True, verbose_name='Latitud')),
                ('longitud', models.FloatField(blank=True, verbose_name='Longitud')),
                ('place_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de lugar (Google Maps)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('descripcion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voluntariado.descripcionvoluntariado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organizacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizacion.organizacion')),
            ],
            options={
                'verbose_name': 'historical voluntariado',
                'verbose_name_plural': 'historical voluntariados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InscripcionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('INS', 'Inscrito'), ('CAN', 'Cancelado'), ('ASI', 'Asistió')], default='INS', max_length=4)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='persona.voluntario')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='voluntariado.turno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalInscripcionTurno',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('INS', 'Inscrito'), ('CAN', 'Cancelado'), ('ASI', 'Asistió')], default='INS', max_length=4)),
                ('fecha_inscripcion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voluntario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persona.voluntario')),
                ('turno', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voluntariado.turno')),
            ],
            options={
                'verbose_name': 'historical inscripcion turno',
                'verbose_name_plural': 'historical inscripcion turnos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Voluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=250)),
                ('requiere_convocatoria', models.BooleanField(default=True, verbose_name='Requiere convocatoria previa para inscribirse')),
                ('fecha_inicio_convocatoria', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de convocatoria')),
                ('fecha_fin_convocatoria', models.DateField(blank=True, null=True, verbose_name='Fecha de fin de convocatoria')),
                ('fecha_inicio_cursado', models.DateField(blank=True, verbose_name='Fecha de inicio de cursado')),
                ('fecha_fin_cursado', models.DateField(blank=True, verbose_name='Fecha de fin de cursado')),
                ('latitud', models.FloatField(blank=True, verbose_name='Latitud')),
                ('longitud', models.FloatField(blank=True, verbose_name='Longitud')),
                ('place_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de lugar (Google Maps)')),
                ('descripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntariados', to='voluntariado.descripcionvoluntariado')),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.organizacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='turno',
            name='voluntariado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='voluntariado.voluntariado'),
        ),
        migrations.CreateModel(
            name='InscripcionConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('INS', 'Inscrito'), ('CAN', 'Cancelado'), ('ACE', 'Aceptado'), ('REJ', 'Rechazado')], default='INS', max_length=4)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_convocatorias', to='persona.voluntario')),
                ('voluntariado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='voluntariado.voluntariado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalTurno',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cupo', models.PositiveIntegerField(default=1)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voluntariado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='voluntariado.voluntariado')),
            ],
            options={
                'verbose_name': 'historical turno',
                'verbose_name_plural': 'historical turnos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
