# Generated by Django 5.2.6 on 2025-09-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionturno',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
