# Generated by Django 5.2.6 on 2025-10-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvoluntariado',
            name='gestionadores',
        ),
        migrations.RemoveField(
            model_name='voluntariado',
            name='gestionadores',
        ),
    ]
