# Generated by Django 5.2.6 on 2025-10-24 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoluntariado',
            name='fecha_fin_convocatoria',
            field=models.DateField(blank=True, default=datetime.date(2025, 10, 24), verbose_name='Fecha de fin de convocatoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalvoluntariado',
            name='fecha_fin_cursado',
            field=models.DateField(blank=True, default=datetime.date(2025, 10, 24), verbose_name='Fecha de fin de cursado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalvoluntariado',
            name='fecha_inicio_convocatoria',
            field=models.DateField(blank=True, default=datetime.date(2025, 10, 24), verbose_name='Fecha de inicio de convocatoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalvoluntariado',
            name='fecha_inicio_cursado',
            field=models.DateField(blank=True, default=datetime.date(2025, 10, 24), verbose_name='Fecha de inicio de cursado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='fecha_fin_convocatoria',
            field=models.DateField(blank=True, default=datetime.date(2025, 10, 24), verbose_name='Fecha de fin de convocatoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='fecha_fin_cursado',
            field=models.DateField(blank=True, default=datetime.date(2025, 10, 24), verbose_name='Fecha de fin de cursado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='fecha_inicio_convocatoria',
            field=models.DateField(blank=True, default=datetime.date(2025, 10, 24), verbose_name='Fecha de inicio de convocatoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='fecha_inicio_cursado',
            field=models.DateField(blank=True, default=datetime.date(2025, 10, 24), verbose_name='Fecha de inicio de cursado'),
            preserve_default=False,
        ),
    ]
