# Generated by Django 5.2.6 on 2025-10-24 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_remove_persona_email'),
        ('voluntariado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('INS', 'Inscrito'), ('CAN', 'Cancelado'), ('ACE', 'Aceptado'), ('REJ', 'Rechazado')], default='INS', max_length=4)),
                ('voluntariado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='voluntariado.voluntariado')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_convocatorias', to='persona.voluntario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
