# Generated by Django 5.2.7 on 2025-10-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvoluntariado',
            name='requiere_convocatoria',
            field=models.BooleanField(default=True, verbose_name='Requiere convocatoria'),
        ),
        migrations.AlterField(
            model_name='voluntariado',
            name='requiere_convocatoria',
            field=models.BooleanField(default=True, verbose_name='Requiere convocatoria'),
        ),
    ]
