# Generated by Django 5.2.7 on 2025-10-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0002_alter_historicalvoluntariado_requiere_convocatoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvoluntariado',
            name='requiere_convocatoria',
            field=models.BooleanField(default=True, verbose_name='Requiere convocatoria previa para inscribirse'),
        ),
        migrations.AlterField(
            model_name='voluntariado',
            name='requiere_convocatoria',
            field=models.BooleanField(default=True, verbose_name='Requiere convocatoria previa para inscribirse'),
        ),
    ]
