# Generated by Django on 2025-11-02
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0002_alter_historicalvoluntariado_requiere_convocatoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntariado',
            name='notificacion_activo_enviada_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
