# Generated by Django 5.2.6 on 2025-10-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0002_historicalvoluntariado_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoluntariado',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de lugar (Google Maps)'),
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de lugar (Google Maps)'),
        ),
    ]
