# Generated by Django 5.2.6 on 2025-10-01 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_gestionador_alter_persona_localidad_administrativo_and_more'),
        ('voluntariado', '0002_inscripcionturno_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionVoluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos')),
                ('portada', models.FileField(blank=True, null=True, upload_to='logos')),
                ('resumen', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='voluntariado',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionturno',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='turno',
            name='voluntariado',
        ),
        migrations.RemoveField(
            model_name='voluntariado',
            name='facultad',
        ),
        migrations.RemoveField(
            model_name='voluntariado',
            name='organizacion',
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='gestionadores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntariados', to='persona.gestionador'),
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntariados', to='voluntariado.turno'),
        ),
        migrations.AlterField(
            model_name='voluntariado',
            name='descripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntariados', to='voluntariado.descripcionvoluntariado'),
        ),
    ]
