# Generated by Django 5.2.6 on 2025-10-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0002_historicalvoluntariado_fecha_fin_convocatoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvoluntariado',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='voluntariado',
            name='estado',
        ),
    ]
