# Generated by Django 5.2.6 on 2025-10-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0002_inscripcionconvocatoria'),
        ('voluntariado', '0003_historicalvoluntariado_place_id_and_more'),
    ]

    operations = [
    ]
