# Generated by Django on 2025-11-02
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0003_voluntariado_notificacion_activo_enviada_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoluntariado',
            name='notificacion_activo_enviada_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
