# Generated by Django 5.2.6 on 2025-10-10 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0004_remove_organizacion_voluntariado'),
        ('voluntariado', '0003_descripcionvoluntariado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voluntariado',
            old_name='gestionadores',
            new_name='gestionadores',
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.organizacion'),
        ),
    ]
