# Generated by Django 5.2.6 on 2025-10-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0004_rename_gestionadores_voluntariado_gestionadores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionturno',
            name='estado',
            field=models.CharField(choices=[('INS', 'Inscrito'), ('CAN', 'Cancelado'), ('ASI', 'Asistió')], default='INS', max_length=4),
        ),
    ]
