# Generated by Django 5.2.6 on 2025-10-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0004_merge_20251025_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvoluntariado',
            name='latitud',
            field=models.FloatField(blank=True, default=0, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalvoluntariado',
            name='longitud',
            field=models.FloatField(blank=True, default=0, verbose_name='Longitud'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voluntariado',
            name='latitud',
            field=models.FloatField(blank=True, default=0, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voluntariado',
            name='longitud',
            field=models.FloatField(blank=True, default=0, verbose_name='Longitud'),
            preserve_default=False,
        ),
    ]
