# Generated by Django 5.2.6 on 2025-10-20 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0005_alter_inscripcionturno_estado'),
    ]


