# Generated by Django 5.2.6 on 2025-10-20 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0005_alter_inscripcionturno_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntariado',
            name='turno',
        ),
        migrations.AddField(
            model_name='turno',
            name='voluntariado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='voluntariado.voluntariado'),
        ),
    ]
