# Generated by Django 5.2.7 on 2025-10-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0005_alter_historicalvoluntariado_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoluntariado',
            name='requiere_convocatoria',
            field=models.BooleanField(default=True, verbose_name='Requiere convocatoria previa para inscribirse'),
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='requiere_convocatoria',
            field=models.BooleanField(default=True, verbose_name='Requiere convocatoria previa para inscribirse'),
        ),
    ]
