# Generated by Django 5.2.6 on 2025-10-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0006_remove_voluntariado_turno_turno_voluntariado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntariado',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='voluntariado',
            name='fecha_inicio',
        ),
    ]
