# Generated by Django 5.2.7 on 2025-10-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0006_historicalvoluntariado_requiere_convocatoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvoluntariado',
            name='fecha_fin_convocatoria',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin de convocatoria'),
        ),
        migrations.AlterField(
            model_name='historicalvoluntariado',
            name='fecha_inicio_convocatoria',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de convocatoria'),
        ),
        migrations.AlterField(
            model_name='voluntariado',
            name='fecha_fin_convocatoria',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin de convocatoria'),
        ),
        migrations.AlterField(
            model_name='voluntariado',
            name='fecha_inicio_convocatoria',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de convocatoria'),
        ),
    ]
