# Generated by Django 5.2.6 on 2025-10-23 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_gestionador_alter_persona_localidad_administrativo_and_more'),
        ('voluntariado', '0008_alter_voluntariado_gestionadores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntariado',
            name='turno',
        ),
        migrations.AddField(
            model_name='turno',
            name='voluntariado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='voluntariado.voluntariado'),
        ),
        migrations.AlterField(
            model_name='historicalvoluntariado',
            name='gestionadores',
            field=models.ForeignKey(blank=True, db_column='gestionadores_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persona.gestionador'),
        ),
        migrations.AlterField(
            model_name='voluntariado',
            name='gestionadores',
            field=models.ForeignKey(db_column='gestionadores_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntariados', to='persona.gestionador'),
        ),
    ]
