# Generated by Django 5.2.7 on 2025-10-28 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultad', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('dni', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicacion.localidad')),
            ],
            options={
                'ordering': ('apellido', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Gestionador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.persona')),
            ],
            options={
                'abstract': False,
            },
            bases=('persona.persona',),
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('gestionador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.gestionador')),
            ],
            options={
                'abstract': False,
            },
            bases=('persona.gestionador',),
        ),
        migrations.CreateModel(
            name='Delegado',
            fields=[
                ('gestionador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.gestionador')),
            ],
            options={
                'abstract': False,
            },
            bases=('persona.gestionador',),
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.persona')),
                ('interno', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('condicion', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Docente', 'Docente'), ('Egresado', 'Egresado'), ('Personal no docente', 'Personal no docente'), ('Intercambio', 'Intercambio')], default='Estudiante', max_length=20)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facultad.carrera')),
            ],
            options={
                'abstract': False,
            },
            bases=('persona.persona',),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['dni'], name='persona_per_dni_3062cc_idx'),
        ),
        migrations.AddField(
            model_name='delegado',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegados', to='organizacion.organizacion'),
        ),
    ]
