# Generated by Django 5.2.6 on 2025-10-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='email',
        ),
    ]
