# Generated by Django 5.2.6 on 2025-09-20 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_alter_organizacion_contacto_persona'),
        ('persona', '0001_initial'),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestionador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.persona')),
            ],
            options={
                'abstract': False,
            },
            bases=('persona.persona',),
        ),
        migrations.AlterField(
            model_name='persona',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicacion.localidad'),
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('gestionador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.gestionador')),
            ],
            options={
                'abstract': False,
            },
            bases=('persona.gestionador',),
        ),
        migrations.CreateModel(
            name='Delegado',
            fields=[
                ('gestionador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.gestionador')),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegados', to='organizacion.organizacion')),
            ],
            options={
                'abstract': False,
            },
            bases=('persona.gestionador',),
        ),
    ]
