# Generated by Django 5.2.6 on 2025-10-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_remove_persona_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='condicion',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Docente', 'Docente'), ('Egresado', 'Egresado'), ('Personal no docente', 'Personal no docente'), ('Intercambio', 'Intercambio')], default='Estudiante', max_length=20),
        ),
    ]
