# Generated by Django 5.2.6 on 2025-09-15 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacitacion', '0001_initial'),
        ('persona', '0001_initial'),
        ('voluntariado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='voluntariado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voluntariado.voluntariado'),
        ),
        migrations.AddField(
            model_name='inscripcioncapacitacion',
            name='capacitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='capacitacion.capacitacion'),
        ),
        migrations.AddField(
            model_name='inscripcioncapacitacion',
            name='voluntario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cap_inscripciones', to='persona.voluntario'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcioncapacitacion',
            unique_together={('capacitacion', 'voluntario')},
        ),
    ]
