# Generated by Django 5.2.6 on 2025-09-08 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacitacion', '0001_initial'),
        ('voluntariados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='voluntariado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voluntariados.voluntariado'),
        ),
        migrations.AddField(
            model_name='inscripcioncapacitacion',
            name='capacitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='capacitacion.capacitacion'),
        ),
    ]
