# Generated by Django 5.2.6 on 2025-10-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settled_up',
            field=models.BooleanField(default=False),
        ),
    ]
